name: Build Release Binaries

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.21

      - name: Display the version of go that we have installed
        run: go version

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: "DEBUG: What's our directory & what's in it?"
        run: pwd && ls

      - name: Build the Rodeo executables
        run: cd emperium; go build -o emperieum

      - name: List the Rodeo executables
        run: ls -l ./release

      - name: Upload the Rodeo binaries
        uses: actions/svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./emperium/emperium
          file_glob: true